[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
$fixtureRoot = Join-Path ([System.IO.Path]::GetTempPath()) "lotus-reservation-$([guid]::NewGuid().ToString('N'))"
$adapterDirectory = Join-Path $fixtureRoot 'lotus-platform/automation'
New-Item -ItemType Directory -Force -Path $adapterDirectory | Out-Null
foreach ($repo in @('core','performance','risk','ai','advise','manage','report','archive','render','idea','gateway','workbench')) {
  New-Item -ItemType Directory -Path (Join-Path $fixtureRoot "lotus-$repo") | Out-Null
}
# A controlled supplier interface, not consumer conformance or production IAM evidence.
$adapter = @'
function Invoke-CanonicalReservation {
  param($Action, $ProjectsRoot, $Holder, $WorkbenchRepoPath, $OperationToken, $RuntimeMode='full')
  $global:proofRuntimeMode=$RuntimeMode
  if (-not $Holder -or $Holder -eq 'foreign') { throw 'RESERVATION_REFUSED' }
  if ($WorkbenchRepoPath -ne $global:proofSelectedWorkbench) { throw 'WORKBENCH_SCOPE_NOT_FORWARDED' }
  if ($Action -eq 'preflight-operation' -and ($global:proofOperationDepth -ne 1 -or $OperationToken -ne 'controlled-admission')) { throw 'UNFENCED_VALIDATION' }
  return @{holder=$Holder}
}
function Enter-CanonicalRuntimeOperation {
  param($ProjectsRoot, $Holder, $Action, $WorkbenchRepoPath, $RuntimeMode='full')
  Invoke-CanonicalReservation -Action preflight -ProjectsRoot $ProjectsRoot -Holder $Holder -WorkbenchRepoPath $WorkbenchRepoPath -RuntimeMode $RuntimeMode | Out-Null
  $global:proofOperationDepth++; $global:proofBegins++
  $scope=if ($global:proofStoredScope) { $global:proofStoredScope } else { [pscustomobject]@{ports=@(3000,8001,8100,8111,8150,8310,8330); sources=[pscustomobject]@{'fixture-full'='controlled-full-source'}} }
  return @{Bindings=@($global:proofAdmittedBindings); Holder=$Holder; Token='controlled-admission'; Scope=$scope}
}
function Assert-CanonicalRuntimeOperationFence {
  param($ProjectsRoot,$OperationToken,[IO.FileStream]$Fence)
  if ($OperationToken -ne 'controlled-admission' -or -not $Fence -or -not $Fence.CanRead -or -not [object]::ReferenceEquals($Fence,$global:proofNestedParentFence)) { throw 'MISSING_LIVE_PARENT_FENCE' }
}
function Exit-CanonicalRuntimeOperation {
  param($Operation, $Outcome)
  if ($Operation.Token -ne 'controlled-admission') { throw 'UNADMITTED_FINISH' }
  $global:proofOutcomes += $Outcome
  $global:proofOperationDepth--
}
Export-ModuleMember -Function Invoke-CanonicalReservation,Enter-CanonicalRuntimeOperation,Assert-CanonicalRuntimeOperationFence,Exit-CanonicalRuntimeOperation
'@
# Fixture artifacts are generated by this test; application source is never rewritten.
Set-Content -LiteralPath (Join-Path $adapterDirectory 'CanonicalRuntimeReservation.psm1') -Value $adapter
function global:docker {
  if ($args[0] -eq 'compose') {
    if ($args[1] -eq 'config') {
      if ((Split-Path (Get-Location).Path -Leaf) -eq $global:proofFailConfigProject) { throw 'SKIPPED_SERVICE_CONFIG_UNRESOLVED' }
      $global:LASTEXITCODE = 0
      return (@{name=(Split-Path (Get-Location).Path -Leaf)} | ConvertTo-Json -Compress)
    }
    $global:proofMutations += (Get-Location).Path
    $global:LASTEXITCODE = if ($global:proofFailAt -eq $global:proofMutations.Count) { 23 } else { 0 }
    return
  }
  $global:LASTEXITCODE = 0
  if ($args[0] -eq 'ps' -and $args -contains '-aq' -and $args -contains 'label=com.docker.compose.project=lotus-core') {
    $global:proofCoreInspections++
    if ($global:proofReplaceAfterInitial -and $global:proofCoreInspections -ge 2) {
      $global:proofComposeContainers[0].Id = 'replacement-full-id'
    }
    return @($global:proofComposeContainers | ForEach-Object { $_.Id })
  }
  if ($args[0] -eq 'ps' -and $args -contains '-aq' -and $args -contains 'label=com.docker.compose.project=lotus-ai') {
    if ($global:proofExpectedAiEnv -and $env:LOTUS_AI_ENV_FILE -ne $global:proofExpectedAiEnv) { throw 'AI_CONFIG_NOT_SCOPED_BEFORE_ADMISSION' }
    return @($global:proofAiContainers | ForEach-Object { $_.Id })
  }
  if ($args[0] -eq 'inspect') {
    $requested=$args
    $selected=@(@($global:proofComposeContainers)+@($global:proofAiContainers) | Where-Object { $requested -contains $_.Id })
    return (ConvertTo-Json -InputObject $selected -Depth 5 -Compress)
  }
  if ($args[0] -eq 'run') { $global:proofIngressRuns++; $global:LASTEXITCODE=$global:proofIngressStatus }
}
function global:Get-NetTCPConnection {
  param($State, $ErrorAction)
  if ($global:proofUnexpectedListener) { return [pscustomobject]@{LocalPort=8100; OwningProcess=4242} }
  if ($global:proofSkippedListener) { return [pscustomobject]@{LocalPort=3000; OwningProcess=4242} }
  return @()
}
function global:Get-Process {
  param($Id, $ErrorAction)
  if ($global:proofExitedListener) { return $null }
  return [pscustomobject]@{Id=4242; ProcessName='foreign-proof'; StartTime=[datetime]'2026-09-15T00:00:00Z'}
}
function global:Stop-Process { throw 'UNAUTHORIZED_PID_DESTRUCTION' }
$cases = @()
$global:proofSelectedWorkbench = $repoRoot
$global:proofAdmittedBindings = @(); $global:proofComposeContainers = @()
$global:proofOperationDepth = 0; $global:proofBegins = 0
$global:proofCoreInspections = 0; $global:proofReplaceAfterInitial = $false
$global:proofAiContainers=@(); $global:proofExpectedAiEnv=''
try {
  foreach ($scriptName in @('Start-LotusFrontOfficeCanonical.ps1','Stop-LotusFrontOfficeCanonical.ps1','Validate-LotusFrontOfficeCanonical.ps1')) {
    foreach ($holder in @('', 'foreign')) {
      $global:proofMutations = @(); $global:proofOutcomes = @(); $refused = $false
      try {
        & (Join-Path $repoRoot "scripts/live/$scriptName") -ProjectsRoot $fixtureRoot -RuntimeHolder $holder
      } catch {
        if ($_.Exception.Message -notmatch 'RESERVATION_REFUSED') { throw }
        $refused = $true
      }
      if (-not $refused -or $global:proofMutations.Count -ne 0) { throw 'Unadmitted runtime I/O occurred' }
      $cases += "$scriptName / missing-or-foreign-holder refuses before I/O"
    }
    $global:proofMutations = @(); $refused = $false
    try {
      & (Join-Path $repoRoot "scripts/live/$scriptName") -ProjectsRoot $fixtureRoot `
        -RuntimeHolder 'fixture-owner' -WorkbenchRepoPath (Join-Path $fixtureRoot 'lotus-workbench')
    } catch {
      if ($_.Exception.Message -notmatch 'Selected Workbench checkout does not match') { throw }
      $refused = $true
    }
    if (-not $refused -or $global:proofMutations.Count -ne 0) { throw 'Mismatched checkout performed I/O' }
    $cases += "$scriptName / different executing checkout refuses before I/O"
  }
  $global:proofMutations = @(); $global:proofOutcomes = @()
  & (Join-Path $repoRoot 'scripts/live/Start-LotusFrontOfficeCanonical.ps1') `
    -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner' -PortOwnershipPreflightOnly
  if ($global:proofMutations.Count -ne 0) { throw 'Read-only preflight mutated runtime' }
  $cases += 'admitted shipped preflight is read-only'
  foreach ($failure in @(0,2)) {
    $global:proofMutations = @(); $global:proofOutcomes = @(); $global:proofFailAt = $failure
    $refused = $false
    try {
      & (Join-Path $repoRoot 'scripts/live/Stop-LotusFrontOfficeCanonical.ps1') `
        -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner'
    } catch {
      if ($_.Exception.Message -notmatch 'exit 23') { throw }
      $refused = $true
    }
    $expected = if ($failure) { 'failure' } else { 'success' }
    $count = if ($failure) { 2 } else { 12 }
    if ($refused -ne [bool]$failure -or $global:proofMutations.Count -ne $count `
        -or $global:proofOutcomes.Count -ne 1 -or $global:proofOutcomes[0] -ne $expected) {
      throw "Untruthful teardown status: expected $expected/$count"
    }
    $cases += "shipped teardown $expected / $count actual Compose invocations"
  }
  $global:proofStoredScope=[pscustomobject]@{ports=@(80,8001,8202); sources=[pscustomobject]@{'lotus-core'='immutable-core'; 'lotus-manage'='immutable-manage'; 'lotus-workbench'='immutable-workbench'; 'lotus-platform'='immutable-platform'}}
  $global:proofFailAt=0; $global:proofFailConfigProject='lotus-ai'
  $global:proofMutations=@(); $global:proofOutcomes=@()
  & (Join-Path $repoRoot 'scripts/live/Stop-LotusFrontOfficeCanonical.ps1') -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner'
  if ($global:proofMutations.Count -ne 2 -or $global:proofOutcomes[0] -ne 'success') { throw 'Partial teardown consulted skipped products' }
  $cases += 'shipped teardown carries acquired four-source scope and ignores unresolved skipped products'
  $global:proofSkippedListener=$true; $global:proofMutations=@(); $global:proofOutcomes=@()
  & (Join-Path $repoRoot 'scripts/live/Stop-LotusFrontOfficeCanonical.ps1') -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner'
  if ($global:proofMutations.Count -ne 2 -or $global:proofOutcomes[0] -ne 'success') { throw 'Partial teardown inspected/destroyed skipped listener' }
  $cases += 'acquired partial teardown leaves coexisting skipped Workbench listener on3000 untouched'
  $global:proofSkippedListener=$false
  $global:proofStoredScope=$null; $global:proofFailConfigProject=''
  $global:proofUnexpectedListener = $true
  $global:proofMutations = @(); $global:proofOutcomes = @(); $refused = $false
  try {
    & (Join-Path $repoRoot 'scripts/live/Stop-LotusFrontOfficeCanonical.ps1') `
      -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner'
  } catch {
    if ($_.Exception.Message -notmatch 'Host process identity changed') { throw }
    $refused = $true
  }
  if (-not $refused -or $global:proofMutations.Count -or $global:proofOutcomes[0] -ne 'failure') {
    throw 'Unadmitted/reused PID was not fenced'
  }
  $cases += 'unexpected/reused PID refuses before destructive I/O'
  $global:proofExitedListener = $true
  $global:proofMutations = @(); $global:proofOutcomes = @(); $global:proofFailAt = 0
  & (Join-Path $repoRoot 'scripts/live/Stop-LotusFrontOfficeCanonical.ps1') -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner'
  if ($global:proofMutations.Count -ne 12 -or $global:proofOutcomes[0] -ne 'success') { throw 'Exited listener poisoned teardown' }
  $cases += 'already exited listener is harmless; full teardown succeeds'
  $global:proofUnexpectedListener = $false; $global:proofExitedListener = $false
  $corePath = Join-Path $fixtureRoot 'lotus-core'
  $global:proofComposeContainers = @([pscustomobject]@{Id='replacement-full-id'; Config=@{Labels=@{
    'com.docker.compose.project'='lotus-core'; 'com.docker.compose.project.working_dir'=$corePath
  }}})
  foreach ($identity in @('stale-admitted-id','replacement-full-id')) {
    $global:proofAdmittedBindings = @(@{kind='container'; id=$identity; project='lotus-core'; checkout=$corePath; ports=@()})
    $global:proofMutations = @(); $global:proofOutcomes = @(); $refused = $false
    try {
      & (Join-Path $repoRoot 'scripts/live/Stop-LotusFrontOfficeCanonical.ps1') -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner'
    } catch {
      if ($_.Exception.Message -notmatch 'Compose container identity/checkout changed') { throw }
      $refused = $true
    }
    $expected = if ($identity -eq 'stale-admitted-id') { 'failure' } else { 'success' }
    $count = if ($refused) { 0 } else { 12 }
    if ($global:proofMutations.Count -ne $count -or $global:proofOutcomes[0] -ne $expected) { throw 'Compose identity fence failed' }
    $cases += "actual Compose ID comparison: $expected/$count downstream mutations"
  }
  $global:proofComposeContainers[0].Config.Labels.'com.docker.compose.project.working_dir' = Join-Path $corePath 'foreign-child'
  $global:proofMutations = @(); $global:proofOutcomes = @(); $refused = $false
  try {
    & (Join-Path $repoRoot 'scripts/live/Stop-LotusFrontOfficeCanonical.ps1') -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner'
  } catch {
    if ($_.Exception.Message -notmatch 'Compose container identity/checkout changed') { throw }
    $refused = $true
  }
  if (-not $refused -or $global:proofMutations.Count) { throw 'Foreign Compose checkout mutated' }
  $cases += 'full ID with wrong checkout refuses before Compose teardown'
  $global:proofAdmittedBindings = @(); $global:proofComposeContainers = @()

  $contractDirectory = Join-Path $fixtureRoot 'lotus-platform/context/contracts'
  New-Item -ItemType Directory -Force -Path $contractDirectory | Out-Null
  # Explicit controlled runtime configuration, not a live/mutable sibling or IAM grant.
  @{dpm_command_center=@{workbench_caller_tenant_id='fixture-tenant'; tenant_id='fixture-tenant';
    portfolio_manager_id='fixture-pm'; book_id='fixture-book'; command_center_as_of_date='2026-04-10'}
  } | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $contractDirectory 'canonical-front-office-demo-data-contract.json')
  function global:powershell { $global:LASTEXITCODE=0 }
  function global:python { $global:proofSeedCalls++; $global:LASTEXITCODE=0 }
  foreach ($late in @($false,$true)) {
    $global:proofComposeContainers = @([pscustomobject]@{Id=$(if ($late) {'admitted-full-id'} else {'replacement-full-id'}); Config=@{Labels=@{
      'com.docker.compose.project'='lotus-core'; 'com.docker.compose.project.working_dir'=$corePath
    }}})
    $global:proofAdmittedBindings = @(@{kind='container'; id='admitted-full-id'; project='lotus-core'; checkout=$corePath; ports=@()})
    $global:proofCoreInspections = 0; $global:proofReplaceAfterInitial = $late
    $global:proofMutations = @(); $global:proofOutcomes = @(); $refused = $false
    try {
      & (Join-Path $repoRoot 'scripts/live/Start-LotusFrontOfficeCanonical.ps1') `
        -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner' -CoreManageOnly -CleanCoreState
    } catch {
      if ($_.Exception.Message -notmatch 'Compose container identity/checkout changed') { throw }
      $refused = $true
    }
    if (-not $refused -or $global:proofMutations.Count -or $global:proofOutcomes[0] -ne 'failure') { throw 'Startup replacement was mutated' }
    $cases += "shipped startup replacement refuses before Compose mutation / late=$late"
  }
  $global:proofReplaceAfterInitial = $false
  $global:proofComposeContainers=@(); $global:proofAdmittedBindings=@()
  $global:proofFailConfigProject='lotus-ai'; $global:proofIngressStatus=0
  if (Test-Path (Join-Path $adapterDirectory 'Invoke-DpmCommandCenterSeed.ps1')) { throw 'Partial startup must prove DPM is absent and not invoked' }
  foreach ($narrow in @($true,$false)) {
    $global:proofMutations=@(); $global:proofOutcomes=@(); $global:proofSeedCalls=0; $refused=$false
    try {
      & (Join-Path $repoRoot 'scripts/live/Start-LotusFrontOfficeCanonical.ps1') `
        -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner' -CoreManageOnly:$narrow
    } catch { if ($_.Exception.Message -notmatch 'SKIPPED_SERVICE_CONFIG_UNRESOLVED') { throw }; $refused=$true }
    if ($global:proofRuntimeMode -ne $(if ($narrow) {'core-manage'} else {'full'}) -or $refused -eq $narrow -or $global:proofOutcomes[0] -ne $(if ($narrow) {'success'} else {'failure'}) `
      -or $global:proofMutations.Count -ne $(if ($narrow) {2} else {0})) { throw "Selected-mode admission scan was not bounded: narrow=$narrow mode=$global:proofRuntimeMode refused=$refused outcome=$($global:proofOutcomes[0]) mutations=$($global:proofMutations.Count)" }
    $cases += "shipped selected-mode startup / skipped AI configuration failure / narrow=$narrow"
  }
  $global:proofFailConfigProject=''
  # Execute the unchanged shipped helper on the governed force-recreate command too.
  $tokens=$null; $parseErrors=$null
  $startAst=[Management.Automation.Language.Parser]::ParseFile((Join-Path $repoRoot 'scripts/live/Start-LotusFrontOfficeCanonical.ps1'),[ref]$tokens,[ref]$parseErrors)
  if ($parseErrors.Count) { throw 'Startup helper parse failed' }
  foreach ($name in @('Invoke-RepoCommand','Invoke-CanonicalComposeCommand','Invoke-ComposeUp','Invoke-WithProcessEnvironment','Resolve-LotusAiEnvFile','Start-CanonicalAi','Invoke-DpmCommandCenterSeed')) {
    $helper=$startAst.Find({param($node) $node -is [Management.Automation.Language.FunctionDefinitionAst] -and $node.Name -eq $name},$true)
    . ([scriptblock]::Create($helper.Extent.Text))
  }
  $ProjectsRoot=$fixtureRoot; $RuntimeHolder='fixture-owner'; $workbenchRepo=$repoRoot; $runtimeMode='full'
  $platformRepo=Join-Path $fixtureRoot 'lotus-platform'; $PortfolioId='business-identifier-not-authority'
  $fixtureSeed=Join-Path $platformRepo 'automation/Invoke-DpmCommandCenterSeed.ps1'
  @'
param($PortfolioId,$ProjectsRoot,$WorkbenchRepoPath,$RuntimeHolder,$RuntimeOperationToken,[IO.FileStream]$RuntimeOperationFence,$RuntimeMode)
$global:proofDpmArguments=$PSBoundParameters
exit $global:proofDpmStatus
'@ | Set-Content -LiteralPath $fixtureSeed
  $parentFence=[IO.File]::Open((Join-Path $fixtureRoot 'controlled-parent.lock'),'OpenOrCreate','ReadWrite','None')
  $runtimeOperation=@{Token='controlled-admission'; Bindings=@(); Lock=$parentFence}
  try {
    foreach ($status in @(23,0)) {
      $global:proofDpmStatus=$status; $refused=$false
      try { Invoke-DpmCommandCenterSeed }
      catch { if ($_.Exception.Message -notmatch 'nested DPM seed failed with exit code 23') { throw }; $refused=$true }
      foreach ($pair in @(@('ProjectsRoot',$fixtureRoot),@('WorkbenchRepoPath',$repoRoot),@('RuntimeHolder','fixture-owner'),@('RuntimeOperationToken','controlled-admission'),@('RuntimeMode','full'),@('PortfolioId',$PortfolioId))) {
        if ($global:proofDpmArguments[$pair[0]] -ne $pair[1]) { throw "Nested DPM changed admitted argument $($pair[0])" }
      }
      if (-not [object]::ReferenceEquals($global:proofDpmArguments.RuntimeOperationFence,$parentFence) -or -not $parentFence.CanRead) { throw 'Nested DPM lost/disposed the actual parent fence' }
      if ($refused -ne [bool]$status) { throw 'Nested DPM native outcome was hidden' }
      $cases += "actual in-process nested DPM helper / unchanged live fence and authority / exit=$status"
    }
  } finally { $parentFence.Dispose() }
  $global:proofOperationDepth=1
  $global:proofComposeContainers=@([pscustomobject]@{Id='replacement-full-id'; Config=@{Labels=@{
    'com.docker.compose.project'='lotus-core'; 'com.docker.compose.project.working_dir'=$corePath
  }}})
  foreach ($identity in @('stale-admitted-id','replacement-full-id')) {
    $runtimeOperation=@{Token='controlled-admission'; Bindings=@(@{kind='container'; id=$identity; project='lotus-core'; checkout=$corePath; ports=@()})}
    $global:proofMutations=@(); $refused=$false
    try { Invoke-CanonicalComposeCommand $corePath 'docker compose up -d --build --force-recreate' }
    catch { if ($_.Exception.Message -notmatch 'Compose container identity/checkout changed') { throw }; $refused=$true }
    $expected=$identity -eq 'stale-admitted-id'
    if ($refused -ne $expected -or $global:proofMutations.Count -ne $(if ($expected) {0} else {1})) { throw 'Force-recreate identity fence failed' }
    $cases += "actual shipped force-recreate helper / refusal=$expected"
  }
  $aiRepo=Join-Path $fixtureRoot 'lotus-ai'
  $aiEnv=Join-Path $aiRepo '.env.example'
  '# controlled configuration' | Set-Content -LiteralPath $aiEnv
  $global:proofAiContainers=@([pscustomobject]@{Id='replacement-ai-id'; Config=@{Labels=@{
    'com.docker.compose.project'='lotus-ai'; 'com.docker.compose.project.working_dir'=$aiRepo
  }}})
  $global:proofExpectedAiEnv=$aiEnv
  $composeUpCommand='docker compose up -d --build --force-recreate'
  $priorAiEnv=$env:LOTUS_AI_ENV_FILE
  foreach ($identity in @('stale-ai-id','replacement-ai-id')) {
    $runtimeOperation=@{Token='controlled-admission'; Bindings=@(@{kind='container'; id=$identity; project='lotus-ai'; checkout=$aiRepo; ports=@()})}
    $global:proofMutations=@(); $refused=$false
    try { Start-CanonicalAi -EnvFile '.env.example' }
    catch { if ($_.Exception.Message -notmatch 'Compose container identity/checkout changed') { throw }; $refused=$true }
    $expected=$identity -eq 'stale-ai-id'
    if ($refused -ne $expected -or $global:proofMutations.Count -ne $(if ($expected) {0} else {1}) `
      -or [string]$env:LOTUS_AI_ENV_FILE -ne [string]$priorAiEnv) { throw "Default AI environment bypassed structural admission/restoration: refusal=$refused expected=$expected mutations=$($global:proofMutations.Count)" }
    $cases += "actual default AI scoped environment / replacement refusal=$expected"
  }
  $global:proofAiContainers=@(); $global:proofExpectedAiEnv=''; $global:proofOperationDepth=0
  $global:proofAdmittedBindings=@(); $global:proofComposeContainers=@()
  foreach ($status in @(23,0)) {
    $global:proofIngressStatus=$status; $global:proofIngressRuns=0; $global:proofSeedCalls=0
    $global:proofMutations=@(); $global:proofOutcomes=@(); $refused=$false
    try {
      & (Join-Path $repoRoot 'scripts/live/Start-LotusFrontOfficeCanonical.ps1') -ProjectsRoot $fixtureRoot -RuntimeHolder 'fixture-owner' -CoreManageOnly
    } catch {
      if ($_.Exception.Message -notmatch 'direct-ingress startup failed with exit code 23') { throw }
      $refused=$true
    }
    $expected=if ($status) {'failure'} else {'success'}
    if ($refused -ne [bool]$status -or $global:proofIngressRuns -ne 1 -or $global:proofOutcomes[0] -ne $expected `
      -or $global:proofSeedCalls -ne $(if ($status) {0} else {1})) { throw 'Ingress native failure was hidden by seed' }
    $cases += "shipped ingress exit$status / $expected; seed is fenced behind successful startup"
  }

  # Actual strict evidence reader; controlled HTTP/browser transports only prove fencing.
  $evidence = Join-Path $fixtureRoot 'evidence'
  New-Item -ItemType Directory -Path $evidence | Out-Null
  @{schemaVersion='lotus-workbench.idea-candidate-seed-evidence.v3'; portfolioId='PB_SG_GLOBAL_BAL_001';
    asOfDate='2026-04-10'; candidateId='idea_high_cash_0123456789abcdef'; lifecycleStatus='ready_for_review';
    runId='controlled-run'; accessScope=@{tenantId='fixture-tenant'; bookId='fixture-book'; portfolioId='PB_SG_GLOBAL_BAL_001'; clientId='fixture-client'};
    sourceObservedAtUtc='2026-09-15T00:00:00.000Z'; evaluatedAtUtc='2026-09-15T00:00:00.000Z';
    lifecycleObservedAtUtc='2026-09-15T00:00:00.000Z'; queueEvaluatedAtUtc='2026-09-15T00:00:00.000Z'
  } | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $evidence 'idea-candidate-seed-evidence.json')
  '{}' | Set-Content -LiteralPath (Join-Path $evidence 'idea-capacity-seed-evidence.json')
  function global:Assert-ProofValidationFence {
    if ($global:proofOperationDepth -ne 1) { throw 'VALIDATION_IO_OUTSIDE_OPERATION' }
    $global:proofObservations++
  }
  function global:Resolve-DnsName { param($Name,$ErrorAction); Assert-ProofValidationFence }
  function global:Invoke-WebRequest { param($Uri,[switch]$UseBasicParsing,$TimeoutSec,$Headers); Assert-ProofValidationFence; return @{StatusCode=200} }
  function global:Invoke-RestMethod {
    param($Uri,$TimeoutSec,$Headers)
    Assert-ProofValidationFence
    if ($Uri -like '*/version') { return @{build=@{ciRunId='controlled-run'}} }
    return @{evaluatedAtUtc='2026-09-15T00:00:00.000Z'; items=@(@{candidate=@{candidateId='idea_high_cash_0123456789abcdef'}})}
  }
  function global:node { Assert-ProofValidationFence; $global:LASTEXITCODE=$global:proofBrowserStatus }
  foreach ($mode in @('standalone','nested','browser-failure')) {
    $global:proofOperationDepth = if ($mode -eq 'nested') { 1 } else { 0 }
    $global:proofBegins = 0; $global:proofOutcomes = @(); $global:proofObservations = 0
    $global:proofBrowserStatus = if ($mode -eq 'browser-failure') { 23 } else { 0 }
    $validationArgs = @{ProjectsRoot=$fixtureRoot; RuntimeHolder='fixture-owner'; CanonicalEvidenceDirectory=$evidence}
    $global:proofNestedParentFence=$null
    if ($mode -eq 'nested') {
      $global:proofNestedParentFence=[IO.File]::Open((Join-Path $fixtureRoot 'nested-validation.lock'),'OpenOrCreate','ReadWrite','None')
      $validationArgs.RuntimeOperationToken='controlled-admission'
      $validationArgs.RuntimeOperationFence=$global:proofNestedParentFence
    }
    $refused = $false
    try {
      & (Join-Path $repoRoot 'scripts/live/Validate-LotusFrontOfficeCanonical.ps1') @validationArgs
    } catch {
      if ($_.Exception.Message -notmatch 'browser validation failed with exit code 23') { throw }
      $refused = $true
    }
    if ($global:proofObservations -lt 20) { throw 'Validation proof did not execute DNS/HTTP/evidence/browser path' }
    if ($mode -eq 'nested') {
      if ($global:proofBegins -ne 0 -or $global:proofOutcomes.Count -ne 0 -or $global:proofOperationDepth -ne 1) { throw 'Nested validation replaced caller operation' }
    } else {
      $expected = if ($refused) { 'failure' } else { 'success' }
      if ($global:proofBegins -ne 1 -or $global:proofOutcomes[0] -ne $expected -or $global:proofOperationDepth -ne 0) { throw 'Standalone validation fence/outcome false' }
    }
    if ($refused -ne ($mode -eq 'browser-failure')) { throw 'Validation failure verdict false' }
    $cases += "admitted $mode executes whole validation under one operation"
    if ($global:proofNestedParentFence) {
      if (-not $global:proofNestedParentFence.CanRead) { throw 'Nested validation closed its parent fence' }
      $global:proofNestedParentFence.Dispose()
    }
  }
  foreach ($mode in @('absent','disposed','foreign')) {
    $global:proofOperationDepth=1; $global:proofObservations=0; $global:proofBegins=0; $global:proofOutcomes=@()
    $global:proofNestedParentFence=[IO.File]::Open((Join-Path $fixtureRoot 'nested-validation.lock'),'OpenOrCreate','ReadWrite','None')
    $otherFence=$null
    $validationArgs=@{ProjectsRoot=$fixtureRoot; RuntimeHolder='fixture-owner'; RuntimeOperationToken='controlled-admission'}
    if ($mode -eq 'disposed') { $global:proofNestedParentFence.Dispose(); $validationArgs.RuntimeOperationFence=$global:proofNestedParentFence }
    if ($mode -eq 'foreign') { $otherFence=[IO.File]::Open((Join-Path $fixtureRoot 'foreign-validation.lock'),'OpenOrCreate','ReadWrite','None'); $validationArgs.RuntimeOperationFence=$otherFence }
    $refused=$false
    try { & (Join-Path $repoRoot 'scripts/live/Validate-LotusFrontOfficeCanonical.ps1') @validationArgs }
    catch { if ($_.Exception.Message -notmatch 'MISSING_LIVE_PARENT_FENCE') { throw }; $refused=$true }
    finally { $global:proofNestedParentFence.Dispose(); if ($otherFence) { $otherFence.Dispose() } }
    if (-not $refused -or $global:proofObservations -or $global:proofBegins -or $global:proofOutcomes.Count) { throw 'Stale token admitted unfenced validation I/O' }
    $cases += "nested validation $mode parent fence refuses before observations"
  }
  @{contract='canonical-runtime-reservation-consumer'; evidence='controlled supplier interface, real shipped scripts'; cases=$cases; passed=$true} | ConvertTo-Json -Depth 4
} finally {
  Remove-Item Function:/docker,Function:/Get-NetTCPConnection,Function:/Get-Process,Function:/Stop-Process -ErrorAction SilentlyContinue
  # Remove only this test's resolved, generated temporary fixture.
  $resolved = (Resolve-Path -LiteralPath $fixtureRoot).Path
  $temporary = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath())
  if (-not $resolved.StartsWith($temporary, [System.StringComparison]::OrdinalIgnoreCase)) { throw 'Invalid fixture cleanup target' }
  Remove-Item -LiteralPath $resolved -Recurse -Force
}
